name: Default
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: "golang:1.13"
    steps:
      - name: install go-task
        run: curl -sL https://taskfile.dev/install.sh | sh
      - name: show env
        run: ./bin/task --version && go version
